### 4) Random Sampling.

In [1]:
import numpy as np

1) **random.rand().**

Random values in a given shape.

In [2]:
# Two dimensional array.
x = np.random.rand(3, 3)
print(x)
print('\n------------------\n')

[[0.51236253 0.31488128 0.6415114 ]
 [0.11949643 0.98482424 0.10577379]
 [0.16879585 0.34979628 0.01172163]]

------------------



In [3]:
# Five dimensional array.
x = np.random.rand(2, 2, 2, 2, 2)
print(x)
print('\n------------------\n')

[[[[[0.21052304 0.70313788]
    [0.12456922 0.96452841]]

   [[0.68670872 0.13202274]
    [0.35194392 0.42383241]]]


  [[[0.94158843 0.43018388]
    [0.51051372 0.56593363]]

   [[0.38668055 0.27764663]
    [0.53306146 0.03161565]]]]



 [[[[0.05547027 0.71362719]
    [0.4107311  0.6013102 ]]

   [[0.88145971 0.38465798]
    [0.79174714 0.35844402]]]


  [[[0.27786631 0.15293871]
    [0.99879244 0.45952771]]

   [[0.88242468 0.65855814]
    [0.06931173 0.53698152]]]]]

------------------



2) **random.randint().**

Returns random integers from low (inclusive) to high (exclusive).

In [4]:
x = np.random.randint(low = 0, high = 9, size = 10)
print(x)
print('\n------------------\n')

[1 8 6 0 5 1 2 2 3 7]

------------------

